name: macOS Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Install TLS client fork (with prebuilt dylibs)
        run: pip install git+https://github.com/blunadev/msp-tls-client.git

      - name: Install other dependencies
        run: pip install -r requirements.txt

      - name: Build macOS binary
        run: pyinstaller --onefile autos.py

      - name: Upload built binary
        uses: actions/upload-artifact@v4
        with:
          name: macos-binary
          path: dist/autos
