name: Build macOS Executable

on:
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install git+https://github.com/xerusmsp/msp-tls-client.git
          python -m pip install pyamf
          python -m pip install pyinstaller

      - name: Determine architecture and set binary path
        run: |
          ARCH=$(uname -m)
          echo "Architecture: $ARCH"
          if [ "$ARCH" = "arm64" ]; then
            echo "DYLIB_PATH=$(python -c 'import msp_tls_client, os; print(os.path.join(os.path.dirname(msp_tls_client.__file__), "dependencies", "tls-client-arm64.dylib"))')" >> $GITHUB_ENV
          else
            echo "DYLIB_PATH=$(python -c 'import msp_tls_client, os; print(os.path.join(os.path.dirname(msp_tls_client.__file__), "dependencies", "tls-client-x86.dylib"))')" >> $GITHUB_ENV
          fi

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile \
            --add-binary "$DYLIB_PATH:msp_tls_client/dependencies" \
            autos.py

      - name: Zip executable
        run: zip -j mac_build.zip dist/autos

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: mac_build.zip
