name: Build macOS Executable

on:
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Upgrade pip, setuptools, wheel
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies
        run: |
          # Install your fork of msp-tls-client
          pip install git+https://github.com/blunadev/msp-tls-client.git
          # Install other dependencies if needed
          pip install -r requirements.txt || true

      - name: Build executable
        run: |
          pip install pyinstaller
          pyinstaller --onefile your_main_script.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-executable
          path: dist/your_main_script
