name: macOS Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install pyinstaller colorama git+https://github.com/blunadev/msp-tls-client.git
          pip install git+https://github.com/hydrix1/pyamf.git

      - name: Build macOS binary
        run: |
          pyinstaller --onefile \
            --hidden-import=pyamf \
            --hidden-import=pyamf.remoting \
            --hidden-import=pyamf.amf3 \
            --hidden-import=colorama \
            autos.py

      - name: Upload built binary
        uses: actions/upload-artifact@v4
        with:
          name: macos-binary
          path: dist/autos
