name: Build macOS Executable

on:
  workflow_dispatch:  # Allows manual trigger from Actions tab

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install git+https://github.com/xerusmsp/msp-tls-client.git
          pip install pyamf

      - name: Build executable
        run: |
          pyinstaller --onefile autos.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS-autos
          path: dist/autos
