name: macos-release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel pyinstaller
          pip install -r requirements.txt || echo "No requirements.txt found"

      - name: Build wheel (offline-safe)
        run: |
          python setup.py sdist bdist_wheel

      - name: Install locally to test
        run: |
          pip install dist/*.whl
          python -c "import msp_tls_client; print('✅ MSP TLS Client loaded successfully')"

      - name: Build standalone binary with PyInstaller
        run: |
          pyinstaller --onefile autos.py
          ls dist/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-binaries
          path: |
            dist/*
            !dist/*.spec
