name: Build macOS Executable

on:
  workflow_dispatch:  # Allows manual triggering from GitHub Actions tab

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install .

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile \
            --add-binary "msp_tls_client/dependencies/tls-client-arm64.dylib:msp_tls_client/dependencies" \
            --add-binary "msp_tls_client/dependencies/tls-client-x86_64.dylib:msp_tls_client/dependencies" \
            autos.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-executable
          path: dist/autos
