name: Build macOS Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyamf
          pip install git+https://github.com/xerusmsp/msp-tls-client.git

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --name "MSP_Autograph_Giver" --icon=jims.ico autos.py

      - name: Zip macOS app
        run: |
          cd dist
          zip -r MSP_Autograph_Giver_macOS.zip MSP_Autograph_Giver

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: dist/MSP_Autograph_Giver_macOS.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
