name: run-macos-binary

on:
  workflow_dispatch:

jobs:
  run-binary:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make binary executable
        run: chmod +x Autograph

      - name: Run binary
        run: ./Autograph
