name: test-macos-binary

on:
  workflow_dispatch: # Run manually from the Actions tab

jobs:
  run:
    runs-on: macos-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: autos
          path: ./bin

      - name: Make executable and run
        run: |
          chmod +x ./bin/autos
          echo "=== Running binary on macOS ==="
          ./bin/autos || echo "Binary exited with non-zero status"
